<?xml version='1.0' encoding='utf-8'?>

<!-- This is the XML file used to design the two forms of 
          jspBeanExample application -->

<!-- DTD for validating this XML file -->

<!DOCTYPE forms [
        <!ELEMENT forms (forms-content-generator?,
                forms-field-validator*,
                forms-field-groupValidator*,
                form+)>
        <!ELEMENT forms-content-generator    EMPTY>
        <!ELEMENT forms-field-validator      EMPTY>
        <!ELEMENT forms-field-groupValidator EMPTY>
        <!ELEMENT form (field+)>
        <!ELEMENT field (field-value*,
                field-required-message?,
                field-required-error-message?,
                field-validator*,
                field-groupValidator?)>
        <!ELEMENT field-value                  (#PCDATA)>
        <!ELEMENT field-required-message       (#PCDATA)>
        <!ELEMENT field-required-error-message (#PCDATA)>
        <!ELEMENT field-validator              (#PCDATA)>
        <!ELEMENT field-groupValidator         (#PCDATA)>

        <!ATTLIST forms-content-generator
                type          CDATA    #REQUIRED>
        <!ATTLIST forms-field-validator
                name          CDATA    #REQUIRED
                type          CDATA    #REQUIRED>
        <!ATTLIST forms-field-groupValidator
                name          CDATA    #REQUIRED
                type          CDATA    #REQUIRED
                errormessage  CDATA   #IMPLIED>
        <!ATTLIST form
                name          CDATA    #REQUIRED
                page          CDATA    #REQUIRED
                action        CDATA    #REQUIRED
                unbound       (false)  #IMPLIED>
        <!ATTLIST field
                name          CDATA    #REQUIRED
                type          CDATA    #REQUIRED
                required      (true | false) #IMPLIED>
        <!ATTLIST field-value
                state         (selected | checked) #IMPLIED>
        ]>


<!-- Following is a guide on what the meaning of each elements is,
           and how to use them for designing your forms. -->


<!-- 

- "forms" element, root element of this XML file.
It represents a collection of "form" elements.

- "forms-content-generator" element, child of "forms".
This element defines the ContentGenerator implementation class that
is responsable for presentation of forms and their respective next pages.
You must insert the full name of this class through "type" attribute.
If there is no "forms-content-generator" element, your application
will use class com.codepassion.form.utils.SimpleContentGenerator.

- "forms-field-validator" element, child of "forms".
This element defines a FieldValidator implementation class that will
be used by one or more fields of one or more forms in this web application.
This element has two required attributes:
"type" attribute, defines a FieldValidator implementation class name.
"name" attribute, identifies the instance that will be created.
The instance created, can be used with more than one fields (within the same 
form or in different forms). 
There can be zero, or more "forms-field-validator" elements in this xml file.

- "forms-field-groupValidator" element, child of "forms".
This element defines a GroupValidator implementation class.
This element has two required and one optional attributes:
"type" attribute defines a GroupValidator implementation class name.
"name" attribute identifies the instance that will be created.
In case the implementation is not field name specific, the created instance, 
can be used in more than one field group, and in more than one form.
PasswordGroup and SimpleGroup provided by FPAPI are such implementation.
"errormessage" attribute does the same thing as setGroupErrorMessage() method 
of GroupValidator does. See javadoc for more details.
There can be zero, one or more "forms-field-groupValidator" elements in this xml file.

- "form" element, child of "forms".
This elements represents one form. There can be as many "form" 
elements as the number of forms in your web module.
Use the required attribute "name" to insert the name of your form.
This name is used as a key for storing this form to the HttpSession, and what is more
important, the URL to this form uses this name to identify the form.
The URL to the form looks like this:
 http://host/yourcontext/forms/yourformname

"page" attribute is required. If you generate form presentation through 
com.codepassion.form.utils.SimpleContentGenerator, use this attribute to insert 
the path to the presentation page of your form (path should be relative to the 
context root).
Otherwise you can use this attribute in the way you need. For example when using XSLT filters
you can use this attribute to insert the path to the XSL file of your form.
You get the value of this attribute back by calling getFormPagePath() method 
of Form object, and you use it when implementing sendFormContent() method of ContentGenerator. 

"action" attribute is required.
This attribute defines the form's action in the classic meaning of "action"
in HTML forms.
If you generate form presentation through com.codepassion.form.utils.SimpleContentGenerator
use this attribute to insert the path to the servlet (or JSP) that handles further processing
of (already validated) form entries.
You get the value of this attribute back by calling getFormActionPath() method 
of Form object, and you use it when implementing forwardToFormAction() method
of ContentGenerator

"unbound" attribute is a flag 'true/false', and it is not required.
When not supplied, the implied value is 'true'.
Value 'true' indicates that the Form object and other objects related
with it must be removed from the session once the form validation succeeds. 
Value 'false' indicates that the Form object and other objects related
with it must be left in the session for being used on further form processing.

- "field" element, child of "form".
This element represents a form field (a FormElement object).
One "form" element can contain one or more "field" elements.
Use "type" attribute to indicate the FPAPI class name of this field.
Use "name" attribute to insert the name of this field.
Use "required" attribute as a flag true/false, indicating whether the
field is required or not.When not supplied, the implied value is 'false', except 
for PasswordBox-es that have it 'true'.

- "field-value" element, child of "field".
If the parent "field" is of type TextBox (text fields, text areas, or
password fields), use this element to enter the field's default value, and 
if there is no default value, don't use this element at all.

If the parent "field" is a subtype of ChoiceBox you must use this element
as many times as the number of the values this field can take, and use 
"state" attribute for those values that are selected or checked by default.
"state" attribute can take the values 'selected' or 'checked' and it's up to you
using the right one for your field.

- "field-required-message" element, child of "field".
Use this element to enter the message that will indicate (the 
first time the form is shown to the client) that the field is required.
In case you don't specify this element, the default "(required)" message is used.

- "field-required-error-message" element, child of "field".
Use this element to enter the message that will indicate (when the 
form is shown back to the client) that the field is required.
In case you don't specify this element, the default "(required field)" message is used.

- "field-validator" element, child of "field".
This element defines the FieldValidator instance that is responsable 
for validating this field's value.
The value of this element must correspond to the "name" attribute's value 
of one of "forms-field-validator" elements defined in this xml file.
There can be zero, or more "field-validator" elements for one "field".

- "field-groupValidator" element, child of "field".
This element defines the GroupValidator instance that is responsable 
for validating this field's value in relation to other fields.
Other fields of the group should share the same GroupValidator instance.
The value of this element must correspond to the "name" attribute's value 
of one of "forms-field-groupValidator" elements defined in this xml file.
There can be zero, or one "field-groupValidator" element for one "field".

-->

<forms>

    <forms-field-validator name="forLogin"
                           type="mypackage.validators.ForLogin"/>

    <forms-field-validator name="forPassword"
                           type="mypackage.validators.ForPassword"/>

    <forms-field-validator name="forNameCountryCityStreet"
                           type="mypackage.validators.ForNameCountryCityStreet"/>

    <forms-field-validator name="forPhone"
                           type="mypackage.validators.ForPhone"/>

    <forms-field-validator name="forPostalCode"
                           type="mypackage.validators.ForPostalCode"/>

    <forms-field-validator name="forNumber"
                           type="mypackage.validators.ForNumber"/>

    <forms-field-groupValidator name="passGroup"
                                type="com.codepassion.form.utils.PasswordGroup"/>

    <forms-field-groupValidator name="contactGroup"
                                type="mypackage.validators.ContactGroup"
                                errormessage="(you must fill here)"/>

    <forms-field-groupValidator name="addressAndWeekpointGroup"
                                type="com.codepassion.form.utils.SimpleGroup"
                                errormessage="(field is required now)"/>

    <forms-field-groupValidator name="servicesGroup"
                                type="mypackage.validators.ServicesGroup"/>

    <form name="registration"
          page="/jsp/registrationForm.jsp"
          action="/servlet/applicationController?action=registration">

        <field name="name"
               type="com.codepassion.form.TextBox">
            <field-validator>
                forNameCountryCityStreet
            </field-validator>
        </field>

        <field name="login"
               type="com.codepassion.form.TextBox"
               required="true">
            <field-required-message>
                (is required)
            </field-required-message>
            <field-required-error-message>
                (please fill this)
            </field-required-error-message>
            <field-validator>
                forLogin
            </field-validator>
        </field>

        <field name="password"
               type="com.codepassion.form.PasswordBox">
            <field-validator>
                forPassword
            </field-validator>
            <field-groupValidator>
                passGroup
            </field-groupValidator>
        </field>

        <field name="passwordAgain"
               type="com.codepassion.form.PasswordBox">
            <field-validator>
                forPassword
            </field-validator>
            <field-groupValidator>
                passGroup
            </field-groupValidator>
        </field>

        <field name="contact"
               type="com.codepassion.form.RadioButton">
            <field-value>
                yes
            </field-value>
            <field-value>
                no
            </field-value>
            <field-required-message>
                (is required)
            </field-required-message>
            <field-required-error-message>
                (please fill this)
            </field-required-error-message>
            <field-groupValidator>
                contactGroup
            </field-groupValidator>
        </field>

        <field name="phone"
               type="com.codepassion.form.TextBox">
            <field-validator>
                forPhone
            </field-validator>
            <field-groupValidator>
                contactGroup
            </field-groupValidator>
        </field>

        <field name="contactTime"
               type="com.codepassion.form.CheckBox">
            <field-value>
                morning
            </field-value>
            <field-value>
                noon
            </field-value>
            <field-value>
                afternoon
            </field-value>
            <field-groupValidator>
                contactGroup
            </field-groupValidator>
        </field>

        <field name="street"
               type="com.codepassion.form.TextBox">
            <field-validator>
                forNameCountryCityStreet
            </field-validator>
            <field-groupValidator>
                addressAndWeekpointGroup
            </field-groupValidator>
        </field>

        <field name="number"
               type="com.codepassion.form.TextBox">
            <field-validator>
                forNumber
            </field-validator>
            <field-groupValidator>
                addressAndWeekpointGroup
            </field-groupValidator>
        </field>

        <field name="postCode"
               type="com.codepassion.form.TextBox">
            <field-validator>
                forPostalCode
            </field-validator>
            <field-groupValidator>
                addressAndWeekpointGroup
            </field-groupValidator>
        </field>

        <field name="city"
               type="com.codepassion.form.TextBox">
            <field-validator>
                forNameCountryCityStreet
            </field-validator>
            <field-groupValidator>
                addressAndWeekpointGroup
            </field-groupValidator>
        </field>

        <field name="country"
               type="com.codepassion.form.TextBox">
            <field-validator>
                forNameCountryCityStreet
            </field-validator>
            <field-groupValidator>
                addressAndWeekpointGroup
            </field-groupValidator>
        </field>

    </form>


    <!-- Following is the Questionnaire Form -->

    <form name="questionnaire"
          page="/jsp/questionnaireForm.jsp"
          action="/servlet/applicationController?action=questionnaire">

        <field name="satisfied"
               type="com.codepassion.form.RadioButton"
               required="true">
            <field-value>
                very satisfied
            </field-value>
            <field-value>
                worth having
            </field-value>
            <field-value>
                not satisfied
            </field-value>
        </field>

        <field name="totalService"
               type="com.codepassion.form.MenuBox">
            <field-value>
            </field-value>
            <field-value>
                1 year
            </field-value>
            <field-value>
                2 years
            </field-value>
            <field-value>
                3 years
            </field-value>
            <field-value>
                4 years
            </field-value>
            <field-value>
                5 years
            </field-value>
            <field-value>
                6 years
            </field-value>
            <field-value>
                7 years
            </field-value>
            <field-groupValidator>
                servicesGroup
            </field-groupValidator>
        </field>

        <field name="services"
               type="com.codepassion.form.MenuBox">
            <field-value>
                Basic Service
            </field-value>
            <field-value>
                Extended Service
            </field-value>
            <field-value>
                Special Service
            </field-value>
            <field-groupValidator>
                servicesGroup
            </field-groupValidator>
        </field>

        <field name="basicService"
               type="com.codepassion.form.MenuBox">
            <field-value>
            </field-value>
            <field-value>
                1 year
            </field-value>
            <field-value>
                2 years
            </field-value>
            <field-value>
                3 years
            </field-value>
            <field-value>
                4 years
            </field-value>
            <field-value>
                5 years
            </field-value>
            <field-value>
                6 years
            </field-value>
            <field-value>
                7 years
            </field-value>
            <field-groupValidator>
                servicesGroup
            </field-groupValidator>
        </field>

        <field name="extendedService"
               type="com.codepassion.form.MenuBox">
            <field-value>
            </field-value>
            <field-value>
                1 year
            </field-value>
            <field-value>
                2 years
            </field-value>
            <field-value>
                3 years
            </field-value>
            <field-value>
                4 years
            </field-value>
            <field-value>
                5 years
            </field-value>
            <field-value>
                6 years
            </field-value>
            <field-value>
                7 years
            </field-value>
            <field-groupValidator>
                servicesGroup
            </field-groupValidator>
        </field>

        <field name="specialService"
               type="com.codepassion.form.MenuBox">
            <field-value>
            </field-value>
            <field-value>
                1 year
            </field-value>
            <field-value>
                2 years
            </field-value>
            <field-value>
                3 years
            </field-value>
            <field-value>
                4 years
            </field-value>
            <field-value>
                5 years
            </field-value>
            <field-value>
                6 years
            </field-value>
            <field-value>
                7 years
            </field-value>
            <field-groupValidator>
                servicesGroup
            </field-groupValidator>
        </field>

        <field name="weakPoint"
               type="com.codepassion.form.RadioButton">
            <field-value>
                marketing
            </field-value>
            <field-value>
                customer service
            </field-value>
            <field-value>
                quality
            </field-value>
            <field-groupValidator>
                addressAndWeekpointGroup
            </field-groupValidator>
        </field>

        <field name="comments"
               type="com.codepassion.form.TextBox">
            <field-groupValidator>
                addressAndWeekpointGroup
            </field-groupValidator>
        </field>

    </form>

</forms>