=== silveremartin-dev/JScience/src/main/resources/org/jscience/astronomy/solarsystem/planets/naturalsatellites.dtd
<!-- entities -->

<!-- the top level element -->
<!ELEMENT natural-satellite (name, mass, volume, equatorial-radius, polar-radius, volumetric-mean-radius, ellipticity, mean-density, surface-gravity, surface-acceleration, escape-velocity, GM, bond-albedo, visual-geometric-albedo, visual-magnitude, solar-irradiance, black-body-temperature, moment-of-inertia, J2, number-of-natural-satellites, planetary-ring-system, semi-major-axis, sidereal-orbit-period, tropical-orbit-period, perihelion, aphelion, synodic-period, mean-orbital-velocity, maximum-orbital-velocity, minimum-orbital-velocity, orbit-inclination, orbit-eccentricity, sidereal-rotation-period, length-of-day, obliquity-to-orbit, surface-pressure, average-temperature, atmospheric-composition)>

<!-- elements -->
<!ELEMENT name                            (#PCDATA)>
<!ELEMENT mass                            (#PCDATA)>
<!ELEMENT volume                          (#PCDATA)>
<!ELEMENT equatorial-radius               (#PCDATA)>
<!ELEMENT polar-radius                    (#PCDATA)>
<!ELEMENT volumetric-mean-radius          (#PCDATA)>
<!ELEMENT ellipticity                     (#PCDATA)>
<!ELEMENT mean-density                    (#PCDATA)>
<!ELEMENT surface-gravity                 (#PCDATA)>
<!ELEMENT surface-acceleration            (#PCDATA)>
<!ELEMENT escape-velocity                 (#PCDATA)>
<!ELEMENT GM                              (#PCDATA)>
<!ELEMENT bond-albedo                     (#PCDATA)>
<!ELEMENT visual-geometric-albedo         (#PCDATA)>
<!ELEMENT visual-magnitude                (#PCDATA)>
<!ELEMENT solar-irradiance                (#PCDATA)>
<!ELEMENT black-body-temperature          (#PCDATA)>
<!ELEMENT moment-of-inertia               (#PCDATA)>
<!ELEMENT J2                              (#PCDATA)>
<!ELEMENT number-of-natural-satellites    (#PCDATA)>
<!ELEMENT planetary-ring-system           (#PCDATA)>
<!ELEMENT semi-major-axis                 (#PCDATA)>
<!ELEMENT sidereal-orbit-period           (#PCDATA)>
<!ELEMENT tropical-orbit-period           (#PCDATA)>
<!ELEMENT perihelion                      (#PCDATA)>
<!ELEMENT aphelion                        (#PCDATA)>
<!ELEMENT synodic-period                  (#PCDATA)>
<!ELEMENT mean-orbital-velocity           (#PCDATA)>
<!ELEMENT maximum-orbital-velocity        (#PCDATA)>
<!ELEMENT minimum-orbital-velocity        (#PCDATA)>
<!ELEMENT orbit-inclination               (#PCDATA)>
<!ELEMENT orbit-eccentricity              (#PCDATA)>
<!ELEMENT sidereal-rotation-period        (#PCDATA)>
<!ELEMENT length-of-day                   (#PCDATA)>
<!ELEMENT obliquity-to-orbit              (#PCDATA)>
<!ELEMENT surface-pressure                (#PCDATA)>
<!ELEMENT average-temperature             (#PCDATA)>
<!ELEMENT atmospheric-composition         (#PCDATA)>

=== silveremartin-dev/JScience/src/main/resources/org/jscience/astronomy/solarsystem/planets/mercury.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE naturalsatellite SYSTEM "naturalsatellites.dtd">
<natural-satellite>
    <name>Mercury</name>
    <mass>0.3302</mass>
    <volume>6.083</volume>
    <equatorial-radius>2439.7</equatorial-radius>
    <polar-radius>2439.7</polar-radius>
    <volumetric-mean-radius>2439.7</volumetric-mean-radius>
    <ellipticity>0.0000</ellipticity>
    <mean-density>5427</mean-density>
    <surface-gravity>3.70</surface-gravity>
    <surface-acceleration>3.70</surface-acceleration>
    <escape-velocity>4.3</escape-velocity>
    <GM>0.02203</GM>
    <bond-albedo>0.119</bond-albedo>
    <visual-geometric-albedo>0.106</visual-geometric-albedo>
    <visual-magnitude>-0.42</visual-magnitude>
    <solar-irradiance>9126.6</solar-irradiance>
    <black-body-temperature>442.5</black-body-temperature>
    <moment-of-inertia>0.33</moment-of-inertia>
    <J2>60.0</J2>
    <number-of-natural-satellites>0</number-of-natural-satellites>
    <planetary-ring-system>No</planetary-ring-system>
    <semi-major-axis>57.91</semi-major-axis>
    <sidereal-orbit-period>87.969</sidereal-orbit-period>
    <tropical-orbit-period>87.968</tropical-orbit-period>
    <perihelion>46.00</perihelion>
    <aphelion>69.82</aphelion>
    <synodic-period>115.88</synodic-period>
    <mean-orbital-velocity>47.87</mean-orbital-velocity>
    <maximum-orbital-velocity>58.98</maximum-orbital-velocity>
    <minimum-orbital-velocity>38.86</minimum-orbital-velocity>
    <orbit-inclination>7.00</orbit-inclination>
    <orbit-eccentricity>0.2056</orbit-eccentricity>
    <sidereal-rotation-period>1407.6</sidereal-rotation-period>
    <length-of-day>4222.6</length-of-day>
    <obliquity-to-orbit>0.01</obliquity-to-orbit>
    <surface-pressure>1E-15</surface-pressure>
    <average-temperature>440</average-temperature>
    <atmospheric-composition>42% Oxygen (O2); 29% Sodium (Na); 22% Hydrogen (H2); 6% Helium (He); 0.5% Potassium (K);
        possible trace amounts of Argon (Ar); Carbon Dioxide (CO2); Water (H2O); Nitrogen (N2); Xenon (Xe); Krypton
        (Kr); Neon (Ne)
    </atmospheric-composition>
</natural-satellite>
